### ISSUE TITLE
deepcopy() of a synapseclient.Synapse object broken after upgrade to 2.2.2

### ISSUE THREAD

**Issue by atpage** [Sage-Bionetworks/synapsePythonClient#794]
# Bug Report

## Operating system

Ubuntu 20.04

## Client version

2.2.2

## Description of the problem

I was running client version 2.0.0.  After upgrading to 2.2.2, I'm not able to `deepcopy` a Synapse object:

```
import copy
import synapseclient
syn = synapseclient.Synapse()
syn.login()
syn_copy = copy.deepcopy(syn)
```
Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 264, in _reconstruct
    y = func(*args)
TypeError: __init__() missing 1 required positional argument: 'max_size'
```

Should I wipe/move my cache and try again?  Figured I'd check before re-pulling 270GB.

**Comment by jkiang13** [comment]
Thanks for this report @atpage. There are some stateful constructs introduced in version 2.1.0 that currently don't support copying (i.e. non default constructor on a child attribute object that does not otherwise have a custom copy implementation).

This is not related to the contents of your cache, and clearing your cache won't avoid this.

It may be possible to reintroduce this support in a future version, but can I ask what your particular use case for copying a Synapse instance is (vs instantiating a new one). What state within the Synapse instance are you wanting to be replicated in a copied instance that precludes instantiating a new instance?

**Comment by atpage** [comment]
I have a Synapse object stored inside another class.  That outer object is what I actually need to `deepcopy`.  So that's where the error came up.

I should be able to work around the issue, now that I know it's intentional.  Worst case I can roll back my `synapseclient` version for now.

Thanks!
